name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install a project with a clean slate
      run: npm ci
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_API_KEY: ${{ secrets.API_KEY }}
    - name: Test
      run: npm test
      env:
        HEADLESS: true
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

